name: snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: utkarshpatg
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/utkarshpatg/utkarshpatg.git repo
          cd repo
          git checkout -b output || git checkout output
          cp -r ../dist/* .
          git add .
         
